### ISSUE TITLE
--z1max not compatible with --gsa-full

### ISSUE THREAD

**Issue by nievergeltlab** [precimed/gsa-mixer#7]
For plsa --gsa-full , the program crashes if I specify --z1max 9.336

The error is as follows:

_Traceback (most recent call last):
  File "/home/amaihofer/software/gsa-mixer-main/precimed/mixer.py", line 11, in <module>
    args.func(args)
  File "/home/amaihofer/software/gsa-mixer-main/precimed/mixer/cli.py", line 1581, in execute_plsa_parser
    params = apply_plsa_univariate_fit_sequence(args, params, results, libbgmg_vec, trait_index)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amaihofer/software/gsa-mixer-main/precimed/mixer/cli.py", line 603, in apply_plsa_univariate_fit_sequence
    assert (args.z1max is None)
AssertionError_

It seems like if you specify to run gsa.full, it sets the following: 
 args.adam_separate_by_chromosome = True (this is on line 1455 of current  cli.py code)

then in line 599 of the code this triggers the if statement, _if args.adam_separate_by_chromosome:_

where it then triggers  assert (args.z1max is None)

Other notes:
In the readme, under the getting started section, there is a heading called 'Perform GSA-MiXeR and MAGMA analyses'. There, --z1max is specified for the baseline and enrichment models. However in that example, there is no specification of --gsa-base and --gsa-full. This confuses me, as the MAGMA.job script does include --gsa-base and --gsa-full, however does not use the  --z1max parameter.

For record, my input command was

python ${MIXER_PY} plsa --gsa-full \
 --trait1-file ${SUMSTATS_FOLDER}/${SUMSTATS_FILE}.chr@.sumstats.gz \
 --out ${OUT_FOLDER}/${SUMSTATS_FILE}_fullv2_rep"$REP" \
 --bim-file ${REFERENCE_FOLDER}/1000G.EUR.QC.@.bim \
 --loadlib-file ${REFERENCE_FOLDER}/1000G.EUR.QC.@.bin \
 --use-complete-tag-indices \
 --go-file /home/amaihofer/auditory_gsa/sets/protein_coding_genes_autosome_ucsc_totalist.txt  \
 --go-file-test /home/amaihofer/auditory_gsa/sets/sets_to_test_autosome_ucsc.txt  \
 --threads $THREADS \
 --extract ${REFERENCE_FOLDER}/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep"$REP".snps \
 --load-params-file ${OUT_FOLDER}/${SUMSTATS_FILE}_basev2_rep"$REP".json \
 --lib  /home/amaihofer/software/gsa-mixer-main/src/build/lib/libbgmg.so  \
 --seed $REP --exclude-ranges MHC --hardprune-r2 0.6  

thanks!

**Comment by ofrei** [comment]
The latest runs in the GSA-MiXeR publication were done with z1max=None, i.e. with this feature disabled. Both README.md and scripts/GSA_MIXER.job are now updated to reflect this.

z1max/z2max flags was introduced for cross-trait MiXeR software, to *investigate the effects of model misspecification, we implemented right-censoring of genome-wide significant SNPs*. The way this was done is through by using CDF instead of PDF in the likelihood function - see formula (7) in https://www.nature.com/articles/s41467-019-10310-0 (online methods). In practice this had a small effect on parameter estimates, and it caused quite a lot of computational challenges in GSA-MiXeR gradient-based optimization. At the end I've made this feature work for point estimates, but it was way too slow for hessian-based estimation of standard errors, thus I had to disable it for GSA-MiXeR.
