### ISSUE TITLE
--l-init  option?

### ISSUE THREAD

**Issue by humanpaingeneticslab** [precimed/gsa-mixer#8]
When running ${MIXER_PY} plsa --gsa-base  I get this error:
error: unrecognized arguments: --l-init -0.25

OK, so which version of gsa-mixer do I have?

${MIXER_PY} --version
mixer.py: error: unrecognized arguments: --version

${MIXER_PY} plsa --version
mixer.py: error: unrecognized arguments: --version

I simply removed it from the command line... (seems to be initialized with this very values from what I can see in the log files)

**Comment by ofrei** [comment]
The parameter was renamed to be ``--l-value``, instead of ``--l-init``. Final analyses in the paper were done with ``--l-value -0.25 --fit l``, which is enforced through ``--gsa-base``. It's OK to simply remove ``--l-init`` from all scripts, as in the latest README.md and scripts/GSA_MIXER.job.

Checking for the version is a major issue, I've opened a separate ticket for this, #15. Throughtout the development I've been relying on ``md5sum mixer.sif``, and tracing md5sum hash in https://github.com/norment/ofrei_repo/blob/main/README.md for all pre-built mixer.sif files. But now I really need a ``MIXER_PY --version`` flag, as you suggested, and consistently bump version whenever there is a change that might affect users.

**Comment by ofrei** [comment]
I'll close this issue as ``--l-init`` is explained, and versioning is tracked by #15.
